replicaCount: 1
image:
  repository: hellofresh-server
  tag: latest
  pullPolicy: Never
service:
  type: NodePort
  port: 3000
  nodePort: 32080
resources:
  limits:
    cpu: 400m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
ingress:
  enabled: true
  annotations: {}
  path: /
  hosts:
    - minikube
env:
  - name: SERVE_PORT
    value: "3000"
  - name: DATABASE_URL
    value: "hellofresh-database-production:27017/hellofresh"
